dist: trusty
language: rust
services: docker
sudo: required
env:
  global:
  - CRATE_NAME=oatool
matrix:
  include:
  - env: TARGET=x86_64-unknown-linux-gnu
  - env: TARGET=x86_64-apple-darwin
    os: osx
before_install: set -e
install:
- sh ci/install.sh
- source ~/.cargo/env || true
script:
- bash ci/script.sh
after_script: set +e
before_deploy:
- sh ci/before_deploy.sh
deploy:
  api_key:
    secure: "tTpkQfD/oorN6tQrEfMPbIritGQN+JJZMbVYWHM8ENYM5GOexDL9rvqKmz3MvOIosoCXHqPj+IsDB/ptQtrnR76APPIqlypqPb66vnR4TrBpgwUgSPhoFdMRZ3/zj1pwhsbTLqxo7atLjNgtDUmJwL1Yx3Q/5/HeVlyzEaAzPArU1Y9lKrhZ2wYtMAU76Tly3nIHiu+lcpOtsDgKSVNQnpj/h/xfygpJBoRp7z23yKbs4w6meVgHTMW8ZqItTAS2RY7gcpc/vc3XaViXdofETOhZOyYjO6TUV6/r9KNsQGg0RwYlVPc8gs4l+7Hws5X4r3a+F1KGbOk7+lVSVV89pWiz2B42S21LEShVJ7tZF3BwFkhTDImDdOxk5L46929rvR1II5D2Dn7iNkmlnVEBwP8Xcl24sQDX/3MubZ+vn6yUVpzGo9mDl6LYYIf0UDlN5tqLAPofRM1D138WHYNCEbI1vqm6M+BrdVLgH+BAP1ifOHTvtZd1AM4UZ+C6Tz77LH2yOu/LwHCdrPNKw9euTCfhj9yIY7W6Lvq5/c+ap3XA+OgMTgzJcPd2L7ZTeDsjqUnxurupZxvXYugKHePPaYVfkRah64uHRNgcWKYakOZ5mBRiUp1zYKjF9uCnGSOS66iZU3Pdl+d90VqzO8dl62D6Ls6+eVn+qx6ru78Iq2c="
  file_glob: true
  file: "$CRATE_NAME-$TRAVIS_TAG-$TARGET.*"
  on:
    condition: "$TRAVIS_RUST_VERSION = stable"
    tags: true
  provider: releases
  skip_cleanup: true
cache: cargo
before_cache:
- chmod -R a+r $HOME/.cargo
branches:
  only:
  - "/^v\\d+\\.\\d+\\.\\d+.*$/"
  - master
notifications:
  email:
    on_success: never
