[package]
name = "oatool"
version = "0.1.2"
authors = ["Jordi Polo Carres <mumismo@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.7"
clap = "2"

[dependencies.openapi]
  git = "https://github.com/JordiPolo/openapi"
  branch = "feature/cloning"
#openapi = { path = "../openapi" }
