[package]
name = "openapi_validation"
version = "0.1.0"
authors = ["Jordi Polo <mumismo@gmail.com>"]

[dependencies]
regex = "0.2"

[dependencies.openapi]
  git = "https://github.com/softprops/openapi"
  commit = "bc778470"